### ISSUE TITLE
Simple way to add STRING, but with no update time

### ISSUE THREAD

**Issue by aracnus** [cthoyt/bioversions#5]
I would like to add STRING (https://string-db.org/) version, using its own API. But it doesn't show the date of last update, just version and URL. Is it ok? It's possible to extract version/date here: https://string-db.org/cgi/access?footer_active_subpage=archive, but using API is much simpler.

**Comment by cthoyt** [comment]
Hi @aracnus, that's a really good point! I pinged the maintainers on twitter to see if they'd amend the API (https://twitter.com/cthoyt/status/1360570698851352577). In the mean time I will add this DB for you
